### ISSUE TITLE
Where is the EXE file?

### ISSUE THREAD

**Issue by demchenko-art** [MinisBett/rxhddt#5]
I can not start the program, because there is no EXE file in the archive.

**Comment by minisbett** [comment]
The exe file is located in the release message above where you can download the zip file. It's called "rxhddt.exe"

**Comment by demchenko-art** [comment]
sorry to bother you, but I really can't find the startup file. The closest I have found is "rxhddt.sin"

**Comment by demchenko-art** [comment]
Everyone, sorry, I found it. Thanks!
