### ISSUE TITLE
problem with HT mod.

### ISSUE THREAD

**Issue by demchenko-art** [MinisBett/rxhddt#6]
Hello! Found a problem. After I load the map with the HT mod into the editor and delete that mod, notes sometimes start to skip during playback, although everything is fine in the original replay. If possible, please correct.

**Comment by minisbett** [comment]
Can you describe what do you mean by "notes sometimes start to skip"?

**Comment by demchenko-art** [comment]
I mean, in a modified replay, sometimes the key does not press the note, which is why the note is counted as a miss. The original replay is fine.

**Comment by minisbett** [comment]
can you send me a video where this issue is seen?

**Comment by demchenko-art** [comment]
the problem has run its course. I'm sorry, have a nice day ^•^
